version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update -y
      - apt-get install -y nodejs npm
      - echo "Installing npm packages"
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'